### PR TITLE
This can conflict with valid Java 8 projects

### PR DESCRIPTION
**Pull request by ghost**
Historically this value was used to denote JDK 1.3 projects from Java 5 projects. So there are quite a few valid Java 8 projects that set it to 5 and can conflict with this cn1lib.
https://stackoverflow.com/questions/51128306/minimum-java-version-required-for-cn1lib-to-work

### CODE REVIEW

**Comment by jsfan3** [comment]
Thank you. Do I have to do something to update the CN1Lib or is it updated automatically?

**Comment by codenameone** [comment]
You need to compile it and submit a PR to the CodenameOneLibs project. At the moment this isn't automatic although it might make sense to automate this with a tool like travis.

**Comment by jsfan3** [comment]
Ok

**Comment by jsfan3** [comment]
FYI I've just added a "Warning for Android" paragraph in the README.md, because after a factory reset of my device this library stopped to work... then I found a solution, as I explained in the readme.

**Pull request merged**
